project:
  type: website
  output-dir: _site
  resources: 
    - "*.mp4"

format: fminxyz-html

execute:
  freeze: auto

filters:
  - fminxyz

website:
  navbar:
    title: false
    logo: logo.svg
    logo-alt: fmin.xyz
    tools:
      - icon: github
        href: https://github.com/MerkulovDaniil/optim
      - icon: youtube
        href: https://www.youtube.com/@fmin
      - icon: telegram
        href: https://t.me/fminxyz
  sidebar: 
    style: "docked"
    collapse-level: 1
    contents: docs/**
  repo-url: https://github.com/MerkulovDaniil/optim
  repo-branch: master
  repo-actions: [edit]
  search: 
    location: navbar
    type: textbox
  twitter-card: true
  favicon: favicon.svg
  margin-footer: |
      <button type="button" name="button" class="btn" id="toggleSpoilers">🔽</button>